# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0004_remove_unique_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackredirect',
            name='token',
        ),
        migrations.RemoveField(
            model_name='token',
            name='access_token',
        ),
        migrations.DeleteModel(
            name='CallbackRedirect',
        ),
    ]
